local TweenService=game:GetService("TweenService")
local ed=(e and e:FindFirstChild("Page-Editor"))or addTab("Editor","https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/png/64/code.png")
local DIR="editor_tabs"
if not isfolder(DIR)then makefolder(DIR)end
local ICON_DIR="fw_icons"
if not isfolder(ICON_DIR)then makefolder(ICON_DIR)end
local function httpget(u)local ok,body=pcall(function()if syn and syn.request then local r=syn.request({Url=u,Method="GET"})return r.Body end;if request then local r=request({Url=u,Method="GET"})return r.Body end;return game:HttpGet(u)end)return ok and body or "" end
local function toAsset(p)local a=""pcall(function()if getcustomasset then a=getcustomasset(p)elseif getsynasset then a=getsynasset(p)else a="rbxasset://"..p end end)return a end
local function ensureIcon(name,url)local p=ICON_DIR.."/"..name..".fwtex"if not isfile(p)then local b=httpget(url)pcall(function()writefile(p,b)end)end;return toAsset(p),p end
local PRIMARY=Color3.fromRGB(120,95,205)
local PRIMARY_ACTIVE=Color3.fromRGB(95,75,175)
local PRIMARY_LIGHT=Color3.fromRGB(155,130,245)
local BTN_TEXT=Color3.new(1,1,1)
local K=Color3.new(0,0,0)
local W=Color3.new(1,1,1)
local MARGIN=0.03
local HEADER_H=0.09
local GAP_H=0.02
local BAR_H=0.10
local contentXScale=1-(MARGIN*2)
local headerY=MARGIN
local editorY=MARGIN+HEADER_H+GAP_H
local barY=1-MARGIN-BAR_H
local editorH=1-(editorY+BAR_H+MARGIN)
local function mkbtn(p,n,t,sz,ps,zi,fn)local b=Instance.new("TextButton")b.Parent=p;b.Name=n;b.BorderSizePixel=0;b.BackgroundColor3=PRIMARY;b.TextColor3=BTN_TEXT;b.Text=t;b.TextSize=13;b.Font=Enum.Font.SourceSans;b.Size=sz or UDim2.new(0,120,0,36);b.Position=ps or UDim2.new(0,0,0,0);b.BackgroundTransparency=0;b.TextWrapped=false;b.TextScaled=false;b.ZIndex=zi or 1;b.TextXAlignment=Enum.TextXAlignment.Center;b.TextYAlignment=Enum.TextYAlignment.Center;local uc=Instance.new("UICorner")uc.Parent=b;uc.CornerRadius=UDim.new(0.7,0);local st=Instance.new("UIStroke")st.Parent=b;st.ApplyStrokeMode=Enum.ApplyStrokeMode.Border;st.Thickness=1;if fn then if y then y(b,fn)else b.MouseButton1Click:Connect(fn)end end;return b end
local function mkimgbtn(parent,name,asset,sz,ps,zi,fn,bg,circle)local b=Instance.new("ImageButton")b.Parent=parent;b.Name=name;b.BackgroundColor3=bg or PRIMARY;b.BorderSizePixel=0;b.BackgroundTransparency=1;b.AutoButtonColor=false;b.Size=sz or UDim2.new(0,120,0,36);b.Position=ps or UDim2.new(0,0,0,0);b.ZIndex=zi or 1;b.Image=asset;b.ScaleType=Enum.ScaleType.Fit;local sc=Instance.new("UIScale")sc.Parent=b;sc.Scale=1;local function tweenScale(s)TweenService:Create(sc,TweenInfo.new(0.08,Enum.EasingStyle.Quad,Enum.EasingDirection.Out),{Scale=s}):Play()end;b.MouseButton1Down:Connect(function()tweenScale(0.94)end)b.MouseLeave:Connect(function()tweenScale(1)end)b.MouseButton1Up:Connect(function()tweenScale(1)end)if circle then local uc=Instance.new("UICorner")uc.Parent=b;uc.CornerRadius=UDim.new(1,0)end;if fn then if y then y(b,fn)else b.MouseButton1Click:Connect(fn)end end;return b end
local function fpath(n)return DIR.."/"..n..".lua"end
local function savefile(n,tx)pcall(function()writefile(fpath(n),tx or "")end)end
local function loadfiletxt(n)local ok,tx=pcall(function()if isfile(fpath(n))then return readfile(fpath(n))else return "" end end)return ok and tx or "" end
local tabs={}local cur="Main"local mainContent=""
local hdr=Instance.new("Frame")hdr.Parent=ed;hdr.Name="EdTabs";hdr.BorderSizePixel=0;hdr.BackgroundColor3=Color3.new(1,1,1);hdr.BackgroundTransparency=1;hdr.Size=UDim2.new(contentXScale,0,HEADER_H,0);hdr.Position=UDim2.new(MARGIN,0,headerY,0);local uc_hdr=Instance.new("UICorner")uc_hdr.Parent=hdr;uc_hdr.CornerRadius=UDim.new(0.18,0);local us_hdr=Instance.new("UIStroke")us_hdr.Parent=hdr;us_hdr.ApplyStrokeMode=Enum.ApplyStrokeMode.Border;us_hdr.Thickness=1
local hll=Instance.new("UIListLayout")hll.Parent=hdr;hll.FillDirection=Enum.FillDirection.Horizontal;hll.HorizontalAlignment=Enum.HorizontalAlignment.Left;hll.VerticalAlignment=Enum.VerticalAlignment.Center;hll.Padding=UDim.new(0,6);hll.SortOrder=Enum.SortOrder.LayoutOrder
local bx=ed:FindFirstChild("EditorBox")if not bx then bx=Instance.new("TextBox")bx.Parent=ed;bx.Name="EditorBox";bx.BorderSizePixel=0;bx.BackgroundColor3=Color3.new(0.15,0.15,0.17);bx.TextColor3=W;bx.TextSize=15;bx.TextWrapped=true;bx.MultiLine=true;bx.ClearTextOnFocus=false;bx.Font=Enum.Font.SourceSans;bx.BackgroundTransparency=0;bx.Size=UDim2.new(contentXScale,0,editorH,0);bx.Position=UDim2.new(MARGIN,0,editorY,0);local uc_bx=Instance.new("UICorner")uc_bx.Parent=bx;uc_bx.CornerRadius=UDim.new(0.06,0)else bx.Size=UDim2.new(contentXScale,0,editorH,0)bx.Position=UDim2.new(MARGIN,0,editorY,0)end
local function findConsoleOut()local pc=e and e:FindFirstChild("Page-Console")if not pc then return nil end;local candidates={"ConsoleOut","Output","Out"}for _,name in ipairs(candidates)do local obj=pc:FindFirstChild(name,true)if obj and obj:IsA("TextBox")then return obj end end;for _,ch in ipairs(pc:GetDescendants())do if ch:IsA("TextBox")then return ch end end;return nil end
local function consoleWrite(line,kind)local tag="["..(kind or "info").."] "local msg=tag..tostring(line)if typeof(rconsoleprint)=="function"then pcall(function()rconsoleprint(msg.."\n")end)end;print(msg)local out=findConsoleOut()if out then local sep=((out.Text or "")~="")and"\n"or"";out.Text=(out.Text or "")..sep..msg;if out.CursorPosition then out.CursorPosition=#out.Text+1 end end end
local function restyle()for n,t in pairs(tabs)do local a=(n==cur)if t.sel then t.sel.Visible=a end;if t.l then t.l.TextColor3=a and PRIMARY_LIGHT or W end end end
local function selectTab(name)cur=name;if name=="Main"then bx.Text=mainContent or""else bx.Text=loadfiletxt(name)end;restyle()end
local ord=1
local function mkTab(name)local px=math.max(62,(#name*8)+(name~="Main"and 34 or 22)+20)local hold=Instance.new("Frame")hold.Parent=hdr;hold.Name="T-"..name;hold.BorderSizePixel=0;hold.BackgroundColor3=PRIMARY;hold.BackgroundTransparency=1;hold.Size=UDim2.new(0,px,1,0);hold.ZIndex=2;hold.LayoutOrder=ord;ord=ord+1;local uc_hold=Instance.new("UICorner")uc_hold.Parent=hold;uc_hold.CornerRadius=UDim.new(0.8,0)local lab=Instance.new("TextLabel")lab.Parent=hold;lab.Name="L";lab.Text=name;lab.TextSize=13;lab.TextColor3=W;lab.Font=Enum.Font.SourceSans;lab.BorderSizePixel=0;lab.BackgroundTransparency=1;lab.Size=UDim2.new(1,0,1,0);lab.Position=UDim2.new(0,0,0,0);lab.TextXAlignment=Enum.TextXAlignment.Center;lab.TextYAlignment=Enum.TextYAlignment.Center;local hit=Instance.new("TextButton")hit.Parent=hold;hit.Name="Hit";hit.BorderSizePixel=0;hit.BackgroundTransparency=1;hit.Text="";hit.TextSize=1;hit.Font=Enum.Font.SourceSans;hit.Size=UDim2.new(1,0,1,0);hit.Position=UDim2.new(0,0,0,0);hit.ZIndex=3;hit.MouseButton1Click:Connect(function()selectTab(name)end)local sel=Instance.new("Frame")sel.Parent=hold;sel.Name="Sel";sel.BorderSizePixel=0;sel.BackgroundColor3=PRIMARY_LIGHT;sel.BackgroundTransparency=0;sel.Size=UDim2.new(1,0,0,2);sel.Position=UDim2.new(0,0,1,-2);sel.ZIndex=4;sel.Visible=false;local uc_sel=Instance.new("UICorner")uc_sel.Parent=sel;uc_sel.CornerRadius=UDim.new(1,0)local close=nil;if name~="Main"then close=Instance.new("TextButton")close.Parent=hold;close.Name="X";close.BorderSizePixel=0;close.BackgroundColor3=PRIMARY_ACTIVE;close.TextColor3=BTN_TEXT;close.Text="X";close.TextSize=12;close.Font=Enum.Font.SourceSans;close.Size=UDim2.new(0,16,0,16);close.Position=UDim2.new(1,-22,0,7);close.BackgroundTransparency=0;close.ZIndex=5;local uc_c=Instance.new("UICorner")uc_c.Parent=close;uc_c.CornerRadius=UDim.new(1,0)close.MouseButton1Click:Connect(function()if tabs[name]then if cur==name then cur="Main"selectTab("Main")end;pcall(function()if isfile(fpath(name))then delfile(fpath(name))end end)tabs[name]=nil;hold:Destroy()restyle()end end)end;tabs[name]={h=hold,l=lab,x=close,sel=sel};return hold end
local ov2=Instance.new("Frame")ov2.Parent=ed;ov2.Name="EdAddOv";ov2.Visible=false;ov2.ZIndex=999;ov2.BorderSizePixel=0;ov2.BackgroundColor3=K;ov2.BackgroundTransparency=0.35;ov2.Size=UDim2.new(1,0,1,0);ov2.Position=UDim2.new(0,0,0,0)
local blk=Instance.new("TextButton")blk.Parent=ov2;blk.Name="Block";blk.BorderSizePixel=0;blk.BackgroundTransparency=1;blk.Size=UDim2.new(1,0,1,0);blk.Position=UDim2.new(0,0,0,0);blk.ZIndex=999;blk.Text=""
local pv=Instance.new("Frame")pv.Parent=ov2;pv.Name="EdAddPv";pv.BorderSizePixel=0;pv.BackgroundColor3=Color3.new(0.6,0.6,0.6);pv.BackgroundTransparency=0;pv.Size=UDim2.new(0,300,0,140);pv.Position=UDim2.new(0.5,-150,0.5,-70);pv.ZIndex=1000;local uc_pv=Instance.new("UICorner")uc_pv.Parent=pv;uc_pv.CornerRadius=UDim.new(0.24,0);local us_pv=Instance.new("UIStroke")us_pv.Parent=pv;us_pv.ApplyStrokeMode=Enum.ApplyStrokeMode.Border;us_pv.Thickness=1
local nb=Instance.new("TextBox")nb.Parent=pv;nb.Name="NameBox";nb.BorderSizePixel=0;nb.BackgroundColor3=Color3.new(0.8,0.8,0.8);nb.BackgroundTransparency=0;nb.Size=UDim2.new(0.86,0,0,34);nb.Position=UDim2.new(0.07,0,0.22,0);nb.TextColor3=W;nb.TextSize=15;nb.TextWrapped=false;nb.MultiLine=false;nb.ClearTextOnFocus=false;nb.Font=Enum.Font.SourceSans;local uc_nb=Instance.new("UICorner")uc_nb.Parent=nb;uc_nb.CornerRadius=UDim.new(0.24,0)nb:GetPropertyChangedSignal("Text"):Connect(function()local t=nb.Text or"";if #t>12 then nb.Text=t:sub(1,12)end end)
local okBtn=mkbtn(pv,"OK","OK",UDim2.new(0,112,0,32),UDim2.new(0.07,0,0.68,0),1001,function()local name=(nb.Text or"Tab"):gsub("[%c%p%s]","")if name==""then name="Tab" end;if name=="Main"then selectTab("Main")ov2.Visible=false return end;if not tabs[name]then mkTab(name)savefile(name,"")end;selectTab(name)ov2.Visible=false end)
local cxBtn=mkbtn(pv,"CX","X",UDim2.new(0,112,0,32),UDim2.new(0.59,0,0.68,0),1001,function()ov2.Visible=false end)
local addAsset=ensureIcon("add_tab","https://raw.githubusercontent.com/OneCreatorX/FrostWare/refs/heads/main/icons/add%20tab.jpg")
local plus=mkimgbtn(hdr,"Plus",addAsset,UDim2.new(0,28,0,28),UDim2.new(0,0,0,0),2147480000,function()nb.Text=""ov2.Visible=true end,nil,true)plus.LayoutOrder=2147480000
blk.MouseButton1Click:Connect(function()ov2.Visible=false end)
local function scanAndBuild()local ok,files=pcall(function()return listfiles(DIR)end)if ok and files then for _,f in ipairs(files)do local filename=f:match("[^/\\]+$")or f;local name=filename:gsub("%.lua$","")if name~=""and name~="Main"then if not tabs[name]then mkTab(name)end end end end end
mkTab("Main")tabs["Main"].h.LayoutOrder=0;ord=1;scanAndBuild();selectTab("Main")
bx:GetPropertyChangedSignal("Text"):Connect(function()if cur=="Main"then mainContent=bx.Text or""else savefile(cur,bx.Text or "")end end)
local bar=Instance.new("Frame")bar.Parent=ed;bar.Name="EdBar";bar.BorderSizePixel=0;bar.BackgroundColor3=Color3.new(1,1,1);bar.BackgroundTransparency=1;bar.Size=UDim2.new(contentXScale,0,BAR_H,0);bar.Position=UDim2.new(MARGIN,0,barY,0);local uc_bar=Instance.new("UICorner")uc_bar.Parent=bar;uc_bar.CornerRadius=UDim.new(0.16,0);local us_bar=Instance.new("UIStroke")us_bar.Parent=bar;us_bar.ApplyStrokeMode=Enum.ApplyStrokeMode.Border;us_bar.Thickness=1
local bl=Instance.new("UIListLayout")bl.Parent=bar;bl.FillDirection=Enum.FillDirection.Horizontal;bl.Padding=UDim.new(0,10);bl.HorizontalAlignment=Enum.HorizontalAlignment.Center;bl.VerticalAlignment=Enum.VerticalAlignment.Center
local toast=Instance.new("Frame")toast.Parent=ed;toast.Name="Toast";toast.BorderSizePixel=0;toast.BackgroundColor3=Color3.new(0,0,0);toast.BackgroundTransparency=1;toast.Size=UDim2.new(0,160,0,32);toast.Position=UDim2.new(0.5,-80,barY-0.02,0);toast.ZIndex=2000;toast.Visible=false;local uc_toast=Instance.new("UICorner")uc_toast.Parent=toast;uc_toast.CornerRadius=UDim.new(0.5,0);local tl=Instance.new("TextLabel")tl.Parent=toast;tl.Name="Label";tl.BackgroundTransparency=1;tl.Size=UDim2.new(1,0,1,0);tl.Position=UDim2.new(0,0,0,0);tl.TextColor3=Color3.new(1,1,1);tl.TextSize=14;tl.Font=Enum.Font.SourceSansSemibold;tl.TextXAlignment=Enum.TextXAlignment.Center;tl.TextYAlignment=Enum.TextYAlignment.Center;tl.TextTransparency=1
local function showToast(msg)toast.Visible=true;toast.BackgroundTransparency=0.15;tl.Text=msg;tl.TextTransparency=0;local t1=TweenService:Create(toast,TweenInfo.new(0.1,Enum.EasingStyle.Quad,Enum.EasingDirection.Out),{BackgroundTransparency=0.15})t1:Play()task.delay(0.9,function()local t2=TweenService:Create(toast,TweenInfo.new(0.18,Enum.EasingStyle.Quad,Enum.EasingDirection.In),{BackgroundTransparency=1})local t3=TweenService:Create(tl,TweenInfo.new(0.18,Enum.EasingStyle.Quad,Enum.EasingDirection.In),{TextTransparency=1})t2:Play()t3:Play()t3.Completed:Wait()toast.Visible=false end)end
local function runCode(code)if not code or code==""then return end;local fn,cerr=loadstring(code)if not fn then consoleWrite(cerr or"Compile error","error")return end;local env=setmetatable({},{__index=getfenv()})env.print=function(...)local parts={}for i=1,select("#",...)do parts[i]=tostring(select(i,...))end;consoleWrite(table.concat(parts,"\t"),"print")end;setfenv(fn,env)local ok,rerr=xpcall(fn,function(er)return debug.traceback(er,2)end)if not ok then consoleWrite(rerr,"error")end end
local icExec=ensureIcon("Execute","https://raw.githubusercontent.com/OneCreatorX/FrostWare/refs/heads/main/icons/Execute.jpg")
local icClear=ensureIcon("Clear","https://raw.githubusercontent.com/OneCreatorX/FrostWare/refs/heads/main/icons/Clear.jpg")
local icPaste=ensureIcon("Paste","https://raw.githubusercontent.com/OneCreatorX/FrostWare/refs/heads/main/icons/Paste.jpg")
local icExecCb=ensureIcon("ExecClip","https://raw.githubusercontent.com/OneCreatorX/FrostWare/refs/heads/main/icons/Executer%20clipboard.jpg")
local function addBarImg(name,asset,onClick)local b=mkimgbtn(bar,name,asset,UDim2.new(0.22,0,0,36),UDim2.new(0,0,0,0),1,onClick,nil,false)return b end
addBarImg("Exec",icExec,function()runCode(bx.Text or"")showToast("Executed")end)
addBarImg("Clear",icClear,function()bx.Text=""showToast("Cleared")end)
addBarImg("Paste",icPaste,function()local s=(getclipboard and getclipboard())or"";if #s>0 then bx.Text=s end;showToast("Pasted")end)
addBarImg("ExecClip",icExecCb,function()local s=(getclipboard and getclipboard())or"";runCode(s)showToast("Executed from clipboard")end)
