local ed=(e and e:FindFirstChild("Page-Editor"))or addTab("Editor","https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/png/64/code.png")
local DIR="editor_tabs";if not isfolder(DIR)then makefolder(DIR)end
local function fpath(n)return DIR.."/"..n..".lua"end
local function savefile(n,tx)pcall(function()writefile(fpath(n),tx or"")end)end
local function loadfiletxt(n)local ok,tx=pcall(function()if isfile(fpath(n))then return readfile(fpath(n))else return"" end end)return ok and tx or"" end
local PRIMARY=Color3.fromRGB(120,95,205);local PRIMARY_ACTIVE=Color3.fromRGB(95,75,175);local PRIMARY_LIGHT=Color3.fromRGB(155,130,245);local BTN_TEXT=C.w;local K=C.k;local W=C.w
local MARGIN=0.03;local HEADER_H=0.09;local GAP_H=0.02;local BAR_H=0.10
local contentXScale=1-(MARGIN*2);local headerY=MARGIN;local editorY=MARGIN+HEADER_H+GAP_H;local barY=1-MARGIN-BAR_H;local editorH=1-(editorY+BAR_H+MARGIN)
local function mkbtn(p,n,t,sz,ps,zi,fn)local b=x("tb",p,{n=n,bs=0,bc=PRIMARY,tc=BTN_TEXT,tx=t,txs=13,ft=F(A.j,E.b,E.n),sz=sz or u(0,120,0,36),ps=ps or u(0,0,0,0),bt=0,zi=zi or 1,tfx=E.cx,tfy=E.cy});x("uc",b,{cr=D(0.7,0)});x("us",b,{ar=E.a,th=1});if fn then y(b,fn)end;return b end
local tabs={};local cur="Main";local mainContent=""
local hdr=x("fr",ed,{n="EdTabs",bs=0,bc=C.w,bt=1,sz=u(contentXScale,0,HEADER_H,0),ps=u(MARGIN,0,headerY,0)});x("uc",hdr,{cr=D(0.18,0)});x("us",hdr,{ar=E.a,th=1})
local hll=Instance.new("UIListLayout");hll.Parent=hdr;hll.FillDirection=Enum.FillDirection.Horizontal;hll.HorizontalAlignment=Enum.HorizontalAlignment.Left;hll.Padding=D(0,6);hll.SortOrder=Enum.SortOrder.LayoutOrder
local area=ed:FindFirstChild("EditorArea");if not area then area=x("fr",ed,{n="EditorArea",bs=0,bc=C.t1,bt=0,sz=u(contentXScale,0,editorH,0),ps=u(MARGIN,0,editorY,0),zi=2});x("uc",area,{cr=D(0.06,0)});x("us",area,{ar=E.a,th=1})else area[M.sz]=u(contentXScale,0,editorH,0);area[M.ps]=u(MARGIN,0,editorY,0)end
local scroll=area:FindFirstChild("CodeScroll");if not scroll then scroll=Instance.new("ScrollingFrame");scroll.Name="CodeScroll";scroll.Parent=area;scroll.BackgroundTransparency=1;scroll.BorderSizePixel=0;scroll.Size=UDim2.fromScale(1,1);scroll.Position=UDim2.fromOffset(0,0);scroll.ScrollBarThickness=8;scroll.CanvasSize=UDim2.fromOffset(0,0);scroll.AutomaticCanvasSize=Enum.AutomaticSize.None;scroll.ClipsDescendants=true end
local bx=scroll:FindFirstChild("EditorBox");local gutter=scroll:FindFirstChild("Gutter")
if not gutter then gutter=Instance.new("TextLabel");gutter.Name="Gutter";gutter.Parent=scroll;gutter.BackgroundTransparency=1;gutter.TextColor3=Color3.fromRGB(180,180,200);gutter.TextXAlignment=Enum.TextXAlignment.Right;gutter.TextYAlignment=Enum.TextYAlignment.Top;gutter.Font=F(R..A.i,E.b,E.n);gutter.TextSize=15;gutter.RichText=false;gutter.Size=UDim2.new(0,44,0,0);gutter.Position=UDim2.fromOffset(6,6)end
if not bx then bx=Instance.new("TextBox");bx.Name="EditorBox";bx.Parent=scroll;bx.BackgroundTransparency=1;bx.BorderSizePixel=0;bx.MultiLine=true;bx.ClearTextOnFocus=false;bx.TextEditable=true;bx.TextColor3=W;bx.TextXAlignment=Enum.TextXAlignment.Left;bx.TextYAlignment=Enum.TextYAlignment.Top;bx.TextWrapped=false;bx.RichText=false;bx.Font=F(R..A.i,E.b,E.n);bx.TextSize=15;bx.Text="";bx.CursorPosition=1 end
local TS=game:GetService("TextService")
local function lineHeight()local v=TS:GetTextSize("A",bx.TextSize,bx.Font,Vector2.new(1000,100000))return math.max(16,math.floor(v.Y+4))end
local function splitLines(t)local lines={};for s in (t.."\n"):gmatch("(.-)\n")do table.insert(lines,s)end;return lines end
local lineStarts={}
local function buildLineStarts(t)local idx=1;lineStarts={1};for c in t:gmatch(".-\n")do idx=idx+#c;table.insert(lineStarts,idx)end end
local function setCursorAtLine(l)local t=bx.Text or"";if l<1 then l=1 end;local lc=#splitLines(t);if l>lc then l=lc end;local pos=lineStarts[l] or 1;bx:CaptureFocus();bx.CursorPosition=pos end
local function layoutEditor()local pad=6;local gw=gutter.Size.X.Offset;local lh=lineHeight();local t=bx.Text or"";local lc=math.max(1,1+select(2,t:gsub("\n","")));local contentH=lc*lh+pad*2;gutter.Text=table.concat((function()local r={}for i=1,lc do r[i]=tostring(i)end;return r end)(),"\n");gutter.Size=UDim2.new(0,gw,0,contentH);gutter.Position=UDim2.fromOffset(pad,pad);bx.Size=UDim2.new(1,-(gw+pad*3),0,contentH);bx.Position=UDim2.fromOffset(gw+pad*2,pad);scroll.CanvasSize=UDim2.new(0,0,0,contentH+pad)end
buildLineStarts(bx.Text or"");layoutEditor()
bx:GetPropertyChangedSignal("Text"):Connect(function()buildLineStarts(bx.Text or"");layoutEditor()end)
scroll:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()layoutEditor()end)
gutter.InputBegan:Connect(function(input)if input.UserInputType==Enum.UserInputType.MouseButton1 or input.UserInputType==Enum.UserInputType.Touch then local y=input.Position.Y-gutter.AbsolutePosition.Y+scroll.CanvasPosition.Y;local lh=lineHeight();local l=math.floor(y/lh)+1;setCursorAtLine(l)end end)
local function findConsoleOut()local pc=e and e:FindFirstChild("Page-Console");if not pc then return nil end;local candidates={"ConsoleOut","Output","Out"}for _,name in ipairs(candidates)do local obj=pc:FindFirstChild(name,true)if obj and obj:IsA("TextBox")then return obj end end;for _,ch in ipairs(pc:GetDescendants())do if ch:IsA("TextBox")then return ch end end end
local function consoleWrite(line,kind)local tag="["..(kind or"info").."] ";local msg=tag..tostring(line);if typeof(rconsoleprint)=="function"then pcall(function()rconsoleprint(msg.."\n")end)end;print(msg);local out=findConsoleOut()if out then local sep=(#(out.Text or"")>0)and"\n"or"";out.Text=(out.Text or"")..sep..msg;if out.CursorPosition then out.CursorPosition=#out.Text+1 end end end
local function restyle()for n,t in pairs(tabs)do local a=(n==cur);t.h[M.bc]=a and PRIMARY_ACTIVE or PRIMARY;if t.g then t.g.Color=a and s(PRIMARY_LIGHT,PRIMARY_ACTIVE)or s(PRIMARY,PRIMARY_ACTIVE)end;if t.sel then t.sel[M.v]=a end end end
local function selectTab(name)cur=name;if name=="Main"then bx.Text=mainContent or""else bx.Text=loadfiletxt(name)end;buildLineStarts(bx.Text or"");layoutEditor();restyle()end
local ord=1
local function mkTab(name)local px=math.max(62,(#name*8)+(name~="Main"and 34 or 22)+20);local hold=x("fr",hdr,{n="T-"..name,bs=0,bc=PRIMARY,bt=0,sz=u(0,px,1,0),zi=2});x("uc",hold,{cr=D(0.8,0)});local st=x("us",hold,{ar=E.a,th=1});local grad=x("ug",hold,{rt=90,Color=s(PRIMARY,PRIMARY_ACTIVE)});hold.LayoutOrder=ord;ord=ord+1;local lab=x("tl",hold,{n="L",tx=name,txs=13,tc=BTN_TEXT,ft=F(A.j,E.b,E.n),bs=0,bt=1,sz=u(1,0,1,0),ps=u(0,0,0,0),tfx=E.cx,tfy=E.cy});local hit=x("tb",hold,{n="Hit",bs=0,bc=PRIMARY,tc=BTN_TEXT,tx="",txs=1,sz=u(1,0,1,0),ps=u(0,0,0,0),bt=1,zi=3});y(hit,function()selectTab(name)end);local sel=x("fr",hold,{n="Sel",bs=0,bc=PRIMARY_LIGHT,bt=0,sz=u(1,0,0,3),ps=u(0,0,1,-3),zi=4,v=false});x("uc",sel,{cr=D(1,0)});local close=nil;if name~="Main"then close=x("tb",hold,{n="X",bs=0,bc=PRIMARY_ACTIVE,tc=BTN_TEXT,ft=F(A.j,E.b,E.n),tx="X",txs=12,sz=u(0,16,0,16),ps=u(1,-22,0,7),bt=0,zi=5,tfx=E.cx,tfy=E.cy});x("uc",close,{cr=D(1,0)});y(close,function()if tabs[name]then if cur==name then cur="Main"selectTab("Main")end;pcall(function()if isfile(fpath(name))then delfile(fpath(name))end end);tabs[name]=nil;hold:Destroy();restyle()end end)end;tabs[name]={h=hold,l=lab,x=close,g=grad,st=st,sel=sel};return hold end
local ov2=x("fr",ed,{n="EdAddOv",v=false,zi=999,bs=0,bc=K,bt=0.35,sz=u(1,0,1,0),ps=u(0,0,0,0)})
local blk=x("tb",ov2,{n="Block",bs=0,bt=1,sz=u(1,0,1,0),ps=u(0,0,0,0),zi=999,tx=""})
local pv=x("fr",ov2,{n="EdAddPv",bs=0,bc=C.g2,bt=0,sz=u(0,300,0,140),ps=u(0.5,-150,0.5,-70),zi=1000});x("uc",pv,{cr=D(0.24,0)});x("us",pv,{ar=E.a,th=1})
local nb=Instance.new("TextBox");nb.Parent=pv;nb[M.n]="NameBox";nb[M.bs]=0;nb[M.bc]=C.t1;nb[M.bt]=0;nb[M.sz]=u(0.86,0,0,34);nb[M.ps]=u(0.07,0,0.22,0);nb[M.tc]=W;nb[M.tfx]=E.lx;nb[M.tfy]=E.ly;nb[M.txs]=15;nb[M.txw]=false;nb.ClearTextOnFocus=false;nb[M.ft]=F(R..A.i,E.b,E.n);x("uc",nb,{cr=D(0.24,0)});nb:GetPropertyChangedSignal("Text"):Connect(function()local t=nb.Text or"";if #t>12 then nb.Text=t:sub(1,12)end end)
local okBtn=mkbtn(pv,"OK","OK",u(0,112,0,32),u(0.07,0,0.68,0),1001,function()local name=(nb.Text or"Tab"):gsub("[%c%p%s]","");if name==""then name="Tab" end;if name=="Main"then selectTab("Main")ov2[M.v]=false return end;if not tabs[name]then mkTab(name)savefile(name,"")end;selectTab(name);ov2[M.v]=false end)
local cxBtn=mkbtn(pv,"CX","X",u(0,112,0,32),u(0.59,0,0.68,0),1001,function()ov2[M.v]=false end)
local plus=mkbtn(hdr,"Plus","+",u(0,26,1,0),u(0,0,0,0),2147480000,function()nb.Text=""ov2[M.v]=true end);x("uc",plus,{cr=D(1,0)});plus.LayoutOrder=2147480000;y(blk,function()ov2[M.v]=false end)
local function scanAndBuild()local ok,files=pcall(function()return listfiles(DIR)end);if ok and files then for _,f in ipairs(files)do local filename=f:match("[^/\\]+$")or f;local name=filename:gsub("%.lua$","");if name~=""and name~="Main"then if not tabs[name]then mkTab(name)end end end end end
mkTab("Main");tabs["Main"].h.LayoutOrder=0;ord=1;scanAndBuild();selectTab("Main")
bx:GetPropertyChangedSignal("Text"):Connect(function()if cur=="Main"then mainContent=bx.Text or""else savefile(cur,bx.Text or"")end end)
local bar=x("fr",ed,{n="EdBar",bs=0,bc=C.w,bt=1,sz=u(contentXScale,0,BAR_H,0),ps=u(MARGIN,0,barY,0)});x("uc",bar,{cr=D(0.16,0)});x("us",bar,{ar=E.a,th=1})
local bl=Instance.new("UIListLayout");bl.Parent=bar;bl.FillDirection=Enum.FillDirection.Horizontal;bl.Padding=D(0,10);bl.HorizontalAlignment=Enum.HorizontalAlignment.Center;bl.VerticalAlignment=Enum.VerticalAlignment.Center
local function addBarBtn(name,label,onClick)local b=mkbtn(bar,name,label,u(0,0,0,36),u(0,0,0,0),1,onClick);b.Size=UDim2.new(0.22,0,0,36);return b end
local function runCode(code)if not code or code==""then return end;local fn,cerr=loadstring(code);if not fn then consoleWrite(cerr or"Compile error","error")return end;local env=setmetatable({}, {__index=getfenv()});env.print=function(...)local parts={}for i=1,select("#",...)do parts[i]=tostring(select(i,...))end;consoleWrite(table.concat(parts,"\t"),"print")end;setfenv(fn,env);local ok,rerr=xpcall(fn,function(er)return debug.traceback(er,2)end);if not ok then consoleWrite(rerr,"error")end end
addBarBtn("Clear","Clear",function()bx.Text=""end)
addBarBtn("Paste","Paste",function()local s=(getclipboard and getclipboard())or"";if #s>0 then bx.Text=s end end)
addBarBtn("Exec","Execute",function()runCode(bx.Text or"")end)
addBarBtn("ExecClip","Exec Clip",function()local s=(getclipboard and getclipboard())or"";runCode(s)end)
